export PROJECT = impact-analysis-api-svc
IMPORT_PATH := ${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/... \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/... \
    --link user-mongo-db:user-mongo-db \
    ${DEV_IMAGE}
